/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ItemId = bigint;
export interface Identity {
    name: string;
    email: string;
    address?: string;
    phone?: string;
}
export interface CreditCard {
    cvv: string;
    billingAddress?: string;
    expiryDate: string;
    cardholderName: string;
    cardNumber: string;
}
export interface VaultData {
    creditCards: Array<[ItemId, CreditCard]>;
    logins: Array<[ItemId, Login]>;
    secureNotes: Array<[ItemId, SecureNote]>;
    identities: Array<[ItemId, Identity]>;
}
export interface SecureNote {
    title: string;
    content: string;
}
export interface Login {
    url?: string;
    username: string;
    password: string;
    notes?: string;
}
export interface backendInterface {
    createCreditCard(card: CreditCard): Promise<ItemId>;
    createIdentity(identity: Identity): Promise<ItemId>;
    createLogin(login: Login): Promise<ItemId>;
    createSecureNote(note: SecureNote): Promise<ItemId>;
    deleteCreditCard(id: ItemId): Promise<void>;
    deleteIdentity(id: ItemId): Promise<void>;
    deleteLogin(id: ItemId): Promise<void>;
    deleteSecureNote(id: ItemId): Promise<void>;
    getAllVaultItems(): Promise<VaultData>;
    getCreditCards(): Promise<Array<[ItemId, CreditCard]>>;
    getIdentities(): Promise<Array<[ItemId, Identity]>>;
    getLogins(): Promise<Array<[ItemId, Login]>>;
    getSecureNotes(): Promise<Array<[ItemId, SecureNote]>>;
    updateCreditCard(id: ItemId, updated: CreditCard): Promise<void>;
    updateIdentity(id: ItemId, updated: Identity): Promise<void>;
    updateLogin(id: ItemId, updated: Login): Promise<void>;
    updateSecureNote(id: ItemId, updated: SecureNote): Promise<void>;
}
import type { CreditCard as _CreditCard, Identity as _Identity, ItemId as _ItemId, Login as _Login, SecureNote as _SecureNote, VaultData as _VaultData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCreditCard(arg0: CreditCard): Promise<ItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCreditCard(to_candid_CreditCard_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCreditCard(to_candid_CreditCard_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createIdentity(arg0: Identity): Promise<ItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.createIdentity(to_candid_Identity_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIdentity(to_candid_Identity_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createLogin(arg0: Login): Promise<ItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLogin(to_candid_Login_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLogin(to_candid_Login_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSecureNote(arg0: SecureNote): Promise<ItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSecureNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSecureNote(arg0);
            return result;
        }
    }
    async deleteCreditCard(arg0: ItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCreditCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCreditCard(arg0);
            return result;
        }
    }
    async deleteIdentity(arg0: ItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIdentity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIdentity(arg0);
            return result;
        }
    }
    async deleteLogin(arg0: ItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLogin(arg0);
            return result;
        }
    }
    async deleteSecureNote(arg0: ItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSecureNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSecureNote(arg0);
            return result;
        }
    }
    async getAllVaultItems(): Promise<VaultData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVaultItems();
                return from_candid_VaultData_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVaultItems();
            return from_candid_VaultData_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreditCards(): Promise<Array<[ItemId, CreditCard]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreditCards();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreditCards();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIdentities(): Promise<Array<[ItemId, Identity]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdentities();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdentities();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogins(): Promise<Array<[ItemId, Login]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogins();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogins();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecureNotes(): Promise<Array<[ItemId, SecureNote]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecureNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecureNotes();
            return result;
        }
    }
    async updateCreditCard(arg0: ItemId, arg1: CreditCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCreditCard(arg0, to_candid_CreditCard_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCreditCard(arg0, to_candid_CreditCard_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateIdentity(arg0: ItemId, arg1: Identity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIdentity(arg0, to_candid_Identity_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIdentity(arg0, to_candid_Identity_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLogin(arg0: ItemId, arg1: Login): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogin(arg0, to_candid_Login_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogin(arg0, to_candid_Login_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSecureNote(arg0: ItemId, arg1: SecureNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSecureNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSecureNote(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CreditCard_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreditCard): CreditCard {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Identity_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Identity): Identity {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Login_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Login): Login {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_VaultData_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VaultData): VaultData {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cvv: string;
    billingAddress: [] | [string];
    expiryDate: string;
    cardholderName: string;
    cardNumber: string;
}): {
    cvv: string;
    billingAddress?: string;
    expiryDate: string;
    cardholderName: string;
    cardNumber: string;
} {
    return {
        cvv: value.cvv,
        billingAddress: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.billingAddress)),
        expiryDate: value.expiryDate,
        cardholderName: value.cardholderName,
        cardNumber: value.cardNumber
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: [] | [string];
    username: string;
    password: string;
    notes: [] | [string];
}): {
    url?: string;
    username: string;
    password: string;
    notes?: string;
} {
    return {
        url: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.url)),
        username: value.username,
        password: value.password,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    address: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email: string;
    address?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: value.email,
        address: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.address)),
        phone: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditCards: Array<[_ItemId, _CreditCard]>;
    logins: Array<[_ItemId, _Login]>;
    secureNotes: Array<[_ItemId, _SecureNote]>;
    identities: Array<[_ItemId, _Identity]>;
}): {
    creditCards: Array<[ItemId, CreditCard]>;
    logins: Array<[ItemId, Login]>;
    secureNotes: Array<[ItemId, SecureNote]>;
    identities: Array<[ItemId, Identity]>;
} {
    return {
        creditCards: from_candid_vec_n9(_uploadFile, _downloadFile, value.creditCards),
        logins: from_candid_vec_n14(_uploadFile, _downloadFile, value.logins),
        secureNotes: value.secureNotes,
        identities: from_candid_vec_n18(_uploadFile, _downloadFile, value.identities)
    };
}
function from_candid_tuple_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ItemId, _CreditCard]): [ItemId, CreditCard] {
    return [
        value[0],
        from_candid_CreditCard_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ItemId, _Login]): [ItemId, Login] {
    return [
        value[0],
        from_candid_Login_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ItemId, _Identity]): [ItemId, Identity] {
    return [
        value[0],
        from_candid_Identity_n20(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ItemId, _Login]>): Array<[ItemId, Login]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ItemId, _Identity]>): Array<[ItemId, Identity]> {
    return value.map((x)=>from_candid_tuple_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ItemId, _CreditCard]>): Array<[ItemId, CreditCard]> {
    return value.map((x)=>from_candid_tuple_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CreditCard_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreditCard): _CreditCard {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Identity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Identity): _Identity {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Login_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Login): _Login {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cvv: string;
    billingAddress?: string;
    expiryDate: string;
    cardholderName: string;
    cardNumber: string;
}): {
    cvv: string;
    billingAddress: [] | [string];
    expiryDate: string;
    cardholderName: string;
    cardNumber: string;
} {
    return {
        cvv: value.cvv,
        billingAddress: value.billingAddress ? candid_some(value.billingAddress) : candid_none(),
        expiryDate: value.expiryDate,
        cardholderName: value.cardholderName,
        cardNumber: value.cardNumber
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    address?: string;
    phone?: string;
}): {
    name: string;
    email: string;
    address: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email,
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url?: string;
    username: string;
    password: string;
    notes?: string;
}): {
    url: [] | [string];
    username: string;
    password: string;
    notes: [] | [string];
} {
    return {
        url: value.url ? candid_some(value.url) : candid_none(),
        username: value.username,
        password: value.password,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
