/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreditCard {
  'cvv' : string,
  'billingAddress' : [] | [string],
  'expiryDate' : string,
  'cardholderName' : string,
  'cardNumber' : string,
}
export interface Identity {
  'name' : string,
  'email' : string,
  'address' : [] | [string],
  'phone' : [] | [string],
}
export type ItemId = bigint;
export interface Login {
  'url' : [] | [string],
  'username' : string,
  'password' : string,
  'notes' : [] | [string],
}
export interface SecureNote { 'title' : string, 'content' : string }
export interface VaultData {
  'creditCards' : Array<[ItemId, CreditCard]>,
  'logins' : Array<[ItemId, Login]>,
  'secureNotes' : Array<[ItemId, SecureNote]>,
  'identities' : Array<[ItemId, Identity]>,
}
export interface _SERVICE {
  'createCreditCard' : ActorMethod<[CreditCard], ItemId>,
  'createIdentity' : ActorMethod<[Identity], ItemId>,
  'createLogin' : ActorMethod<[Login], ItemId>,
  'createSecureNote' : ActorMethod<[SecureNote], ItemId>,
  'deleteCreditCard' : ActorMethod<[ItemId], undefined>,
  'deleteIdentity' : ActorMethod<[ItemId], undefined>,
  'deleteLogin' : ActorMethod<[ItemId], undefined>,
  'deleteSecureNote' : ActorMethod<[ItemId], undefined>,
  'getAllVaultItems' : ActorMethod<[], VaultData>,
  'getCreditCards' : ActorMethod<[], Array<[ItemId, CreditCard]>>,
  'getIdentities' : ActorMethod<[], Array<[ItemId, Identity]>>,
  'getLogins' : ActorMethod<[], Array<[ItemId, Login]>>,
  'getSecureNotes' : ActorMethod<[], Array<[ItemId, SecureNote]>>,
  'updateCreditCard' : ActorMethod<[ItemId, CreditCard], undefined>,
  'updateIdentity' : ActorMethod<[ItemId, Identity], undefined>,
  'updateLogin' : ActorMethod<[ItemId, Login], undefined>,
  'updateSecureNote' : ActorMethod<[ItemId, SecureNote], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];