/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreditCard = IDL.Record({
  'cvv' : IDL.Text,
  'billingAddress' : IDL.Opt(IDL.Text),
  'expiryDate' : IDL.Text,
  'cardholderName' : IDL.Text,
  'cardNumber' : IDL.Text,
});
export const ItemId = IDL.Nat;
export const Identity = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Login = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'password' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const SecureNote = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const VaultData = IDL.Record({
  'creditCards' : IDL.Vec(IDL.Tuple(ItemId, CreditCard)),
  'logins' : IDL.Vec(IDL.Tuple(ItemId, Login)),
  'secureNotes' : IDL.Vec(IDL.Tuple(ItemId, SecureNote)),
  'identities' : IDL.Vec(IDL.Tuple(ItemId, Identity)),
});

export const idlService = IDL.Service({
  'createCreditCard' : IDL.Func([CreditCard], [ItemId], []),
  'createIdentity' : IDL.Func([Identity], [ItemId], []),
  'createLogin' : IDL.Func([Login], [ItemId], []),
  'createSecureNote' : IDL.Func([SecureNote], [ItemId], []),
  'deleteCreditCard' : IDL.Func([ItemId], [], []),
  'deleteIdentity' : IDL.Func([ItemId], [], []),
  'deleteLogin' : IDL.Func([ItemId], [], []),
  'deleteSecureNote' : IDL.Func([ItemId], [], []),
  'getAllVaultItems' : IDL.Func([], [VaultData], []),
  'getCreditCards' : IDL.Func([], [IDL.Vec(IDL.Tuple(ItemId, CreditCard))], []),
  'getIdentities' : IDL.Func([], [IDL.Vec(IDL.Tuple(ItemId, Identity))], []),
  'getLogins' : IDL.Func([], [IDL.Vec(IDL.Tuple(ItemId, Login))], []),
  'getSecureNotes' : IDL.Func([], [IDL.Vec(IDL.Tuple(ItemId, SecureNote))], []),
  'updateCreditCard' : IDL.Func([ItemId, CreditCard], [], []),
  'updateIdentity' : IDL.Func([ItemId, Identity], [], []),
  'updateLogin' : IDL.Func([ItemId, Login], [], []),
  'updateSecureNote' : IDL.Func([ItemId, SecureNote], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreditCard = IDL.Record({
    'cvv' : IDL.Text,
    'billingAddress' : IDL.Opt(IDL.Text),
    'expiryDate' : IDL.Text,
    'cardholderName' : IDL.Text,
    'cardNumber' : IDL.Text,
  });
  const ItemId = IDL.Nat;
  const Identity = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Login = IDL.Record({
    'url' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'password' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const SecureNote = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const VaultData = IDL.Record({
    'creditCards' : IDL.Vec(IDL.Tuple(ItemId, CreditCard)),
    'logins' : IDL.Vec(IDL.Tuple(ItemId, Login)),
    'secureNotes' : IDL.Vec(IDL.Tuple(ItemId, SecureNote)),
    'identities' : IDL.Vec(IDL.Tuple(ItemId, Identity)),
  });
  
  return IDL.Service({
    'createCreditCard' : IDL.Func([CreditCard], [ItemId], []),
    'createIdentity' : IDL.Func([Identity], [ItemId], []),
    'createLogin' : IDL.Func([Login], [ItemId], []),
    'createSecureNote' : IDL.Func([SecureNote], [ItemId], []),
    'deleteCreditCard' : IDL.Func([ItemId], [], []),
    'deleteIdentity' : IDL.Func([ItemId], [], []),
    'deleteLogin' : IDL.Func([ItemId], [], []),
    'deleteSecureNote' : IDL.Func([ItemId], [], []),
    'getAllVaultItems' : IDL.Func([], [VaultData], []),
    'getCreditCards' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ItemId, CreditCard))],
        [],
      ),
    'getIdentities' : IDL.Func([], [IDL.Vec(IDL.Tuple(ItemId, Identity))], []),
    'getLogins' : IDL.Func([], [IDL.Vec(IDL.Tuple(ItemId, Login))], []),
    'getSecureNotes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ItemId, SecureNote))],
        [],
      ),
    'updateCreditCard' : IDL.Func([ItemId, CreditCard], [], []),
    'updateIdentity' : IDL.Func([ItemId, Identity], [], []),
    'updateLogin' : IDL.Func([ItemId, Login], [], []),
    'updateSecureNote' : IDL.Func([ItemId, SecureNote], [], []),
  });
};

export const init = ({ IDL }) => { return []; };